### ISSUE TITLE
Remove Guid Requirement

### ISSUE THREAD

**Issue by philmea** [Volkanco/AzureDeploy#1]
Remove the GUID requirement by implementing Azure ARM template function "uniqueString".

**Comment by Volkanco** [comment]
I forgot about this, sorry. 

Unfortunately we need a guid which is unique across Azure and even uniquesting is deterministic. It doesnt create a new one  for each deployment.  in my v2 templates I started used guid function and utilize deployment name , resource group and user provided string to calculate guid.
